app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

student_add:
    path:     /student/new
    defaults: { _controller: AppBundle:Student:createStudent }

student_list:
    path:     /student/list
    defaults: { _controller: AppBundle:Student:list}

student_specific_list:
    path:     /student/list/{studentID}
    defaults: { _controller: AppBundle:Student:showSpecificStudent }

student_delete:
    path:     /student/delete
    defaults: { _controller: AppBundle:Student:delete}

course_add:
    path: /course/new
    defaults: { _controller: AppBundle:Student:addCourse}